### ISSUE TITLE
Any plans for 1.0?

### ISSUE THREAD

**Issue by zacharytamas** [stevewirts/fin-hypergrid-dnd-list#1]
Any plans for updating this to Polymer 1.0? I need this exact functionality currently but can't drop this into my 1.0 project :(

**Comment by stevewirts** [comment]
Hi Zachary,
Are current plans are to move the dnd lists off of polymer 0.5 and be
technology agnostic.
Meaning it will work with conventional techniques.  At that point it should
be trivial to plug in as a polymer component.
~steve
